apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: app-store-integration
  annotations:
    "store.halo.run/app-id": "app-VYJbF"
spec:
  enabled: true
  requires: ">=2.9.0"
  author:
    name: Halo OSS Team
    website: https://github.com/halo-dev
  logo: logo.svg
  homepage: https://github.com/halo-dev/plugin-app-store
  displayName: "应用市场"
  description: "Console 集成 Halo 官方应用市场"
  settingName: plugin-app-store-integration-setting
  configMapName: plugin-app-store-integration-configmap
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/plugin-app-store/blob/main/LICENSE"
